### ISSUE TITLE
write after end

### ISSUE THREAD

**Issue by laggingreflex** [dominictarr/connect-restreamer#8]
Getting this error

    Error: write after end
       at ClientRequest.OutgoingMessage.write (_http_outgoing.js:413:15)
       at IncomingMessage.ondata (_stream_readable.js:540:20)
       at IncomingMessage.emit (events.js:107:17)
       at C:\...\node_modules\connect-restreamer\index.js:18:13
       at process._tickCallback (node.js:355:11)

Using this simple code: [gist]. Getting the error only on POST requests, probably when something with body parsing is involved.

[gist]: https://gist.github.com/laggingreflex/46da9348f599c6c25ec4

**Comment by leejefon** [comment]
In the index.js, the call next() is before process.nextTick()
I moved it to after process.nextTick() and it worked
The problem with this solution is that you are directly modifying the required module, but I guess since the code is not a lot, it should be easy
